# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(blank=True, null=True)),
                ('ipMaquina', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('cons', 'Consitente'), ('inco', 'Inconsistente')], default='Consistente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('frequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativa', to='ponto.Frequencia')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('adimisao', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(null=True)),
                ('salario', models.FloatField(blank=True, max_length=20)),
                ('horario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ponto.Horario')),
            ],
        ),
        migrations.CreateModel(
            name='TipoRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='frequencia',
            name='chefe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chefe', to='ponto.Pessoa'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Funcionario', to='ponto.Pessoa'),
        ),
    ]
