# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0003_auto_20171113_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='chefe',
            field=models.BooleanField(default=False, verbose_name='Chefe?'),
        ),
    ]
